_supported_image_types = {"bmp",
                          "dib",
                          "eps",
                          "gif",
                          "hdr",
                          "jfif",
                          "jp2",
                          "jpe",
                          "jpeg",
                          "jpg",
                          "pbm",
                          "pcx",
                          "pgm",
                          "pic",
                          "png",
                          "pnm",
                          "ppm",
                          "ras",
                          "sgi",
                          "sr",
                          "tiff",
                          "webp",
                          "j2k"}
supported_image_types = {prefix + image_format for image_format in _supported_image_types for prefix in [".", ""]}
