name: CI labeling

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - 'VERSION'
      - 'docs/source/changelog.rst'
  push:
    branches:
    - develop
    - master
    paths-ignore:
      - 'VERSION'
      - 'docs/source/changelog.rst'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Run tests for labeling
      run: |
        test="true" docker compose -f labeling/docker-compose.yml up --build --exit-code-from test
